name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: "10.1.0"
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
        cache: "pnpm"
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ""

    - name: install frontend dependencies
      run: pnpm install

    - uses: actions/setup-java@v4
      if: matrix.platform == 'ubuntu-latest'
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Set up Android SDK
      if: matrix.platform == 'ubuntu-latest'
      uses: android-actions/setup-android@v3
    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true

    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        releaseId: "qing-otp"
        args: ""
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: |
          src-tauri/target/release/bundle
          src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
