name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, android]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
    - name: Install
      run: |
        npm i -g pnpm
        pnpm install
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Set up Android SDK
      if: matrix.platform == 'android'
      uses: android-actions/setup-android@v3

    - name: Set up Android NDK
      if: matrix.platform == 'android'
      run: |
        sudo apt-get install -y --no-install-recommends unzip
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d /usr/local/lib
        echo "export ANDROID_NDK_HOME=/usr/local/lib/android-ndk-r25b" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Build Tauri android app
      if: matrix.platform == 'android'
      uses: tauri-apps/tauri-action@v0
      with:
        args: 'aarch64-linux-android'

    - name: Build Tauri win app
      if: matrix.platform == 'win'
      uses: tauri-apps/tauri-action@v0

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: |
          src-tauri/target/release/bundle
          src-tauri/target/aarch64-linux-android/release/*.apk