name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: "10.1.0"
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
        cache: "pnpm"
    - uses: dtolnay/rust-toolchain@stable

    - name: install frontend dependencies
      run: pnpm install

    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        releaseId: "qing-otp"
        args: ""
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: |
          src-tauri/target/release/bundle

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "10.1.0"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "pnpm"
      - uses: dtolnay/rust-toolchain@stable
        targets: "stable-x86_64-pc-windows-msvc,aarch64-linux-android"

      - run: pnpm install
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: android-actions/setup-android@v3
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          local-cache: true

      - uses: tauri-apps/tauri-action@v0
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          releaseId: "qing-otp"
          args: "--target aarch64-linux-android"
      - uses: actions/upload-artifact@v4
        with:
          name: "qing-otp"
          path: src-tauri/gen/android/app/build/outputs/apk/release/*.apk
