name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: "10.1.0"
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
        cache: "pnpm"
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ""

    - name: install frontend dependencies
      run: pnpm install

    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ""
