name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: "10.1.0"
    - uses: actions/setup-node@v4
      with:
        node-version: "20.17.0"
        cache: "pnpm"
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ""

    - name: install frontend dependencies
      run: pnpm install

    - uses: actions/setup-java@v4
      if: matrix.platform == 'ubuntu-latest'
      with:
          distribution: "temurin"
          java-version: "17"
    - name: Set up Android SDK
      if: matrix.platform == 'ubuntu-latest'
      uses: android-actions/setup-android@v3

    - name: Set up Android NDK
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get install -y --no-install-recommends unzip
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d /usr/local/lib
        echo "export ANDROID_NDK_HOME=/usr/local/lib/android-ndk-r25b" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
        pnpm tauri android build

    - uses: tauri-apps/tauri-action@v0
      if: matrix.platform != 'ubuntu-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        releaseId: "qing-otp"
        args: ""
    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: |
          src-tauri/target/release/bundle
          src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
